# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex Nackenoff | Neuropharmacologist at Vanderbilt
email: anackenoff@gmail.com
public-key: Public Key
email3: alex@alexnackenoff.com
email2: alex.nackenoff@vanderbilt.edu
description: This is my website for topics spanning from Neuroscience and Medicine to my hobbies
    and interests in technology, homebrewing, music, and culture

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alexnackenoff.com" # the base hostname & protocol for your site
twitter_username: anackenoff
github_username:  alex-nackenoff
linkedin_username: alex-nackenoff
pubmed_username: nackenoff
fingerprint: 2BD3 CD93 CB88 47B2 E5C4 E8D9 85BA D36E D672 C2D6

# Build settings
markdown: kramdown
