# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex Nackenoff | Neuropharmacologist at Vanderbilt University
email: anackenoff@gmail.com
email2: alex.nackenoff@vanderbilt.edu
description: This is my website for topics spanning from Neuroscience and Medicine to my hobbies
    and interests in technology, homebrewing, music, politics, and culture

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alex-nackenoff.github.io" # the base hostname & protocol for your site
twitter_username: anackenoff
github_username:  alex-nackenoff

# Build settings
markdown: kramdown
